spring:
  jpa:
    open-in-view: false # OSIV false -> persistence context alive during transaction
  profiles:
    include: oauth,real-db
  session:
    store-type: jdbc
server:
  port: 8081
  servlet:
    encoding:
      force: true
      charset: UTF-8