spring:
  jpa:
    show_sql: true
    open-in-view: false # OSIV false -> persistence context alive during transaction
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  h2:
    console:
      enabled: true
  profiles:
    include: oauth
server:
  port: 8081