spring:
  profiles:
    include: oauth
  jpa:
    open-in-view: false # OSIV false -> persistence context alive during transaction
    show_sql: true
  session:
    store-type: jdbc
server:
  servlet:
    encoding:
      force: true
      charset: UTF-8