spring:
  jpa:
    show_sql: true
    open-in-view: false # OSIV false -> persistence context alive during transaction
  h2:
    console:
      enabled: true
  profiles:
    include: oauth
  session:
    store-type: jdbc
server:
  port: 8081